export type SiteLanguage = "en" | "pt";

export const SITE_COPY: Record<SiteLanguage, Record<string, string>> = {
  en: {
    "dashboard.activeCenter": "Active center",
    "dashboard.atsPipeline": "ATS Pipeline",
    "dashboard.careersPage": "Careers page",
    "dashboard.emailAutomation": "Email automation",
    "dashboard.intake": "Intake",
    "dashboard.job": "Job",
    "dashboard.manageJobs": "Manage jobs",
    "dashboard.morePipelineActions": "More pipeline actions",
    "dashboard.parse": "Parse",
    "dashboard.rank": "Rank",
    "dashboard.resume": "Resume",
    "dashboard.searchAria": "Search candidates, jobs, skills",
    "dashboard.searchPlaceholder": "Search candidates, jobs, skills",
    "dashboard.switchToEnglish": "Switch language to English",
    "dashboard.switchToPortuguese": "Switch language to Portuguese",
    "dashboard.workspaceDefault": "Operations Coordinator - Hybrid Sao Paulo",
    "nav.admin": "Admin",
    "nav.aiMatching": "AI Matching",
    "nav.analytics": "Analytics",
    "nav.applications": "Applications",
    "nav.candidates": "Candidates",
    "nav.careers": "Careers Page",
    "nav.dashboard": "Dashboard",
    "nav.home": "Aptelys Home",
    "nav.emailAutomation": "Email Automation",
    "nav.interviews": "Interviews",
    "nav.jobs": "Jobs",
    "nav.organization": "Organization",
    "nav.recruitmentCrm": "by Interellis",
    "nav.settings": "Settings",
    "nav.signOut": "Sign out",
    "nav.workspaceUsers": "Pro workspace",
  },
  pt: {
    "dashboard.activeCenter": "Central ativa",
    "dashboard.atsPipeline": "Pipeline ATS",
    "dashboard.careersPage": "Página de carreiras",
    "dashboard.emailAutomation": "Automação de email",
    "dashboard.intake": "Entrada",
    "dashboard.job": "Vaga",
    "dashboard.manageJobs": "Gerenciar vagas",
    "dashboard.morePipelineActions": "Mais ações do pipeline",
    "dashboard.parse": "Analisar",
    "dashboard.rank": "Ranquear",
    "dashboard.resume": "Currículo",
    "dashboard.searchAria": "Buscar candidatos, vagas e competências",
    "dashboard.searchPlaceholder": "Buscar candidatos, vagas e competências",
    "dashboard.switchToEnglish": "Alterar idioma para inglês",
    "dashboard.switchToPortuguese": "Alterar idioma para português",
    "dashboard.workspaceDefault": "Coordenador de Opera\u00e7\u00f5es - H\u00edbrido S\u00e3o Paulo",
    "nav.admin": "Admin",
    "nav.aiMatching": "Matching IA",
    "nav.analytics": "Análises",
    "nav.applications": "Aplicações",
    "nav.candidates": "Candidatos",
    "nav.careers": "Página de carreiras",
    "nav.dashboard": "Painel",
    "nav.home": "Inicio Aptelys",
    "nav.emailAutomation": "Automação de email",
    "nav.interviews": "Entrevistas",
    "nav.jobs": "Vagas",
    "nav.organization": "Organização",
    "nav.recruitmentCrm": "by Interellis",
    "nav.settings": "Configurações",
    "nav.signOut": "Sair",
    "nav.workspaceUsers": "workspace Pro",
  },
};

const KEYED_ENGLISH_TO_PORTUGUESE = Object.fromEntries(
  Object.keys(SITE_COPY.en).map((key) => [SITE_COPY.en[key], SITE_COPY.pt[key]]),
);

export const ENGLISH_TO_PORTUGUESE: Record<string, string> = {
  ...KEYED_ENGLISH_TO_PORTUGUESE,
  "Account details": "Dados da conta",
  "Account recovery": "Recupera\u00e7\u00e3o de conta",
  "Address details": "Complemento",
  "Address line": "Endere\u00e7o",
  "AI recruiting for modern hiring teams.": "Recrutamento com IA para equipes modernas.",
  "AI recruiting CRM for every hiring team.": "CRM de recrutamento com IA para qualquer equipe de contrata\u00e7\u00e3o.",
  "Back to account": "Voltar para dados da conta",
  "Back to address": "Voltar para endere\u00e7o",
  "Back to login details": "Voltar para dados de login",
  "Aptelys sends a code to your work email.": "A Aptelys envia um c\u00f3digo para seu email de trabalho.",
  "Aptelys will send a 6-digit code to your work email.": "A Aptelys enviar\u00e1 um c\u00f3digo de 6 d\u00edgitos para seu email de trabalho.",
  "Aptelys will verify this owner account by email.": "A Aptelys verificar\u00e1 esta conta de propriet\u00e1rio por email.",
  "Cannot access your account?": "N\u00e3o consegue acessar sua conta?",
  City: "Cidade",
  "Company address": "Endere\u00e7o da empresa",
  "Company workspace setup": "Configura\u00e7\u00e3o do espa\u00e7o da empresa",
  Continue: "Continuar",
  Country: "Pa\u00eds",
  "Create and verify workspace": "Criar e verificar espa\u00e7o",
  "Create company space": "Criar espa\u00e7o da empresa",
  "Create the company space, verify the owner account, and enter a focused ATS for jobs, candidates, interviews, and automation.": "Crie o espa\u00e7o da empresa, verifique a conta do propriet\u00e1rio e entre em um ATS focado em vagas, candidatos, entrevistas e automa\u00e7\u00f5es.",
  "After 5 failed login attempts, Aptelys will route you to password recovery automatically.": "Depois de 5 tentativas de login com falha, a Aptelys encaminha voc\u00ea automaticamente para a recupera\u00e7\u00e3o de senha.",
  "Enter the ATS with persistent access until the user signs out.": "Entre no ATS com acesso persistente at\u00e9 o usu\u00e1rio sair da conta.",
  "Enter the code sent to your work email.": "Informe o c\u00f3digo enviado ao seu email de trabalho.",
  "Enter the 6-digit code sent to your email.": "Informe o c\u00f3digo de 6 d\u00edgitos enviado ao seu email.",
  "Enter your recruiting command center.": "Entre na sua central de comando de recrutamento.",
  "Enter your work email and Aptelys will route password recovery instructions for the matching workspace account.": "Informe seu email de trabalho e a Aptelys encaminhar\u00e1 as instru\u00e7\u00f5es de recupera\u00e7\u00e3o para a conta correspondente do espa\u00e7o.",
  "Enter your work email to request password recovery.": "Informe seu email de trabalho para solicitar recupera\u00e7\u00e3o de senha.",
  "Forgot password?": "Esqueceu a senha?",
  "If this email belongs to an Aptelys workspace, recovery instructions will be sent or routed to the workspace owner.": "Se este email pertencer a um espa\u00e7o Aptelys, as instru\u00e7\u00f5es de recupera\u00e7\u00e3o ser\u00e3o enviadas ou encaminhadas ao propriet\u00e1rio do espa\u00e7o.",
  "Launch a recruiting workspace without the noise.": "Lance um espa\u00e7o de recrutamento sem ru\u00eddo.",
  "Name the company, agency, or recruiter brand that will own hiring data.": "Nomeie a empresa, ag\u00eancia ou marca do recrutador que ser\u00e1 dona dos dados de contrata\u00e7\u00e3o.",
  "Owner + recruiter access": "Acesso de propriet\u00e1rio + recrutador",
  "Persistent login": "Login persistente",
  "Persistent session": "Sess\u00e3o persistente",
  "Phone number": "Telefone",
  "Postal code": "CEP",
  "Public candidate flow": "Fluxo p\u00fablico do candidato",
  "Confirm and enter": "Confirmar e entrar",
  "Recover access to your recruiting workspace.": "Recupere o acesso ao seu espa\u00e7o de recrutamento.",
  "Recover password": "Recuperar senha",
  "Role-based access": "Acesso por pap\u00e9is",
  "Protected workspace": "Espa\u00e7o protegido",
  "Security check": "Verifica\u00e7\u00e3o de seguran\u00e7a",
  "Email verification": "Verifica\u00e7\u00e3o por email",
  "Secure workspace access": "Acesso seguro ao espa\u00e7o",
  "Secure recovery flow": "Fluxo seguro de recupera\u00e7\u00e3o",
  "Selected verification": "Verifica\u00e7\u00e3o selecionada",
  "Send recovery instructions": "Enviar instru\u00e7\u00f5es de recupera\u00e7\u00e3o",
  "Sign in details": "Dados de login",
  "Sign in, confirm the trusted device, and continue managing jobs, candidates, interviews, automations, and analytics.": "Entre, confirme o dispositivo confi\u00e1vel e continue gerenciando vagas, candidatos, entrevistas, automa\u00e7\u00f5es e an\u00e1lises.",
  "Start hiring": "Come\u00e7ar a contratar",
  "State / region": "Estado / regi\u00e3o",
  "Continue to verification": "Continuar para verifica\u00e7\u00e3o",
  "Tell Aptelys who owns this workspace.": "Informe \u00e0 Aptelys quem \u00e9 respons\u00e1vel por este espa\u00e7o.",
  "Too many login attempts. For your security, recover your password before trying again.": "Muitas tentativas de login. Para sua seguran\u00e7a, recupere sua senha antes de tentar novamente.",
  "Use the email connected to your workspace.": "Use o email conectado ao seu espa\u00e7o.",
  "Verification expired. Sign in again to continue.": "Verifica\u00e7\u00e3o expirada. Entre novamente para continuar.",
  "Where should this workspace be registered?": "Onde este espa\u00e7o deve ser registrado?",
  "Workspace email check": "Verifica\u00e7\u00e3o do email do espa\u00e7o",
  "A company, agency, or independent recruiter starts a secure hiring workspace.": "Uma empresa, ag\u00eancia ou recrutador independente inicia um espa\u00e7o seguro de contrata\u00e7\u00e3o.",
  "AI matching": "Compatibilidade com IA",
  "Backend Platform": "Plataforma Backend",
  "Compare candidates against role requirements with ranking and match context.": "Compare candidatos com os requisitos da vaga usando classifica\u00e7\u00e3o e contexto de compatibilidade.",
  "Coordinate interviews, self-scheduling links, and calendar sync.": "Coordene entrevistas, links de autoagendamento e sincronização de calendário.",
  "Create roles, manage requisitions, and organize hiring ownership.": "Crie vagas, gerencie requisições e organize os responsáveis pela contratação.",
  "Create workspace": "Criar espa\u00e7o",
  "Job CRM": "CRM de vagas",
  "Operate the pipeline": "Operar o funil",
  "Resumes are parsed, matched, and ranked against each role.": "Currículos são analisados, comparados e ranqueados para cada vaga.",
  "Resume intelligence": "Inteligência de currículos",
  "Scheduling": "Agendamento",
  "Senior Full Stack": "Full Stack Sênior",
  "Send candidate updates from templates when key hiring events happen.": "Envie atualiza\u00e7\u00f5es aos candidatos a partir de modelos quando eventos importantes acontecerem.",
  "Track funnel health, score quality, time in stage, and hiring outcomes.": "Acompanhe sa\u00fade do funil, qualidade das pontua\u00e7\u00f5es, tempo em etapa e resultados de contrata\u00e7\u00e3o.",
  "Upload resumes, extract structured profiles, and keep every document attached.": "Envie currículos, extraia perfis estruturados e mantenha cada documento anexado.",
  "Create a workspace and start as the owner/recruiter.": "Crie um espa\u00e7o e comece como propriet\u00e1rio/recrutador.",
  Home: "Início",
  "Open jobs become public application pages while the ATS stays private.": "Vagas abertas viram páginas públicas de candidatura enquanto o ATS permanece privado.",
  "Receive security codes by email.": "Receba códigos de segurança por email.",
  "Aptelys by Interellis workspace": "Espa\u00e7o Aptelys by Interellis",
  "Aptelys home": "In\u00edcio Aptelys",
  "Aptelys brings jobs, candidates, resume parsing, ranking, interviews, and automation into one clean recruiting workspace.": "A Aptelys une vagas, candidatos, an\u00e1lise de curr\u00edculos, ranqueamento, entrevistas e automa\u00e7\u00f5es em um espa\u00e7o de recrutamento limpo.",
  "Aptelys helps companies, agencies, and independent recruiters manage roles, resumes, interviews, and hiring analytics across any industry.": "A Aptelys ajuda empresas, ag\u00eancias e recrutadores independentes a gerenciar vagas, curr\u00edculos, entrevistas e an\u00e1lises de contrata\u00e7\u00e3o em qualquer setor.",
  "Aptelys keeps the browser signed in after verification, so recruiters do not need to authenticate on every page.": "A Aptelys mant\u00e9m o navegador conectado depois da verifica\u00e7\u00e3o, ent\u00e3o recrutadores n\u00e3o precisam se autenticar em cada p\u00e1gina.",
  "Your password": "Sua senha",
  "Access your application timeline.": "Acesse a linha do tempo da sua candidatura.",
  "After signing in, this browser stays authenticated until you sign out, clear cookies, change devices, or the session is revoked.": "Depois de entrar, este navegador permanece autenticado até você sair, limpar cookies, trocar de dispositivo ou a sessão ser revogada.",
  "After signup, Aptelys opens a verification step before entering the workspace.": "Depois do cadastro, a Aptelys abre uma etapa de verifica\u00e7\u00e3o antes de entrar no espa\u00e7o.",
  "AI ranked": "Ranqueado por IA",
  "AI recruiting software for real hiring operations.": "Software de recrutamento com IA para operações reais de contratação.",
  "AI recruitment CRM for companies, agencies, and independent recruiters.": "CRM de recrutamento com IA para empresas, agências e recrutadores independentes.",
  "Already have a workspace?": "J\u00e1 tem um espa\u00e7o?",
  "Application access": "Acesso à candidatura",
  "Back to sign in": "Voltar ao login",
  "Back to signup": "Voltar ao cadastro",
  "Back to Aptelys home": "Voltar para o in\u00edcio da Aptelys",
  "Browse public opportunities published by the hiring workspace. This page is separate from the internal Aptelys recruiter dashboard.": "Veja oportunidades p\u00fablicas publicadas pelo espa\u00e7o de contrata\u00e7\u00e3o. Esta p\u00e1gina \u00e9 separada do painel interno de recrutadores da Aptelys.",
  "Browse published jobs and apply directly through the public candidate experience.": "Veja vagas publicadas e candidate-se diretamente pela experiência pública do candidato.",
  "Built for the paying customer.": "Criado para o cliente que usa a plataforma.",
  "Calendar ready": "Agenda pronta",
  "Candidate portal": "Portal do candidato",
  "Candidates do not need an internal Aptelys account. Use the secure link or token sent after applying to follow your hiring timeline.": "Candidatos n\u00e3o precisam de uma conta interna na Aptelys. Use o link seguro ou token enviado ap\u00f3s a candidatura para acompanhar sua linha do tempo.",
  "Candidates stay in a clean public experience. Recruiters operate the full ATS behind authenticated workspaces.": "Candidatos ficam em uma experi\u00eancia p\u00fablica limpa. Recrutadores operam o ATS completo por tr\u00e1s de espa\u00e7os autenticados.",
  "Company or recruiter brand": "Empresa ou marca do recrutador",
  "Company/recruiter workspace": "Espa\u00e7o da empresa/recrutador",
  "Confirm this trusted sign-in.": "Confirme este login confiável.",
  "Create a hiring workspace that is ready to operate.": "Crie um espa\u00e7o de contrata\u00e7\u00e3o pronto para operar.",
  "Create an account, launch a workspace, invite recruiters, and manage your hiring operation.": "Crie uma conta, lance um espa\u00e7o, convide recrutadores e gerencie sua opera\u00e7\u00e3o de contrata\u00e7\u00e3o.",
  "Create and enter workspace": "Criar e entrar no espa\u00e7o",
  "Create the workspace": "Criar o espa\u00e7o",
  "Development email code": "Código de email para desenvolvimento",
  "Email code": "Código por email",
  "Explore public roles and submit your resume without entering the internal recruiter workspace.": "Veja vagas p\u00fablicas e envie seu curr\u00edculo sem acessar o espa\u00e7o interno dos recrutadores.",
  "Fill every required field to create your workspace.": "Preencha todos os campos obrigat\u00f3rios para criar seu espa\u00e7o.",
  "Finish protecting your new workspace.": "Finalize a prote\u00e7\u00e3o do seu novo espa\u00e7o.",
  "For candidates": "Para candidatos",
  "For companies": "Para empresas",
  "For companies and recruiters": "Para empresas e recrutadores",
  "For companies, agencies, and independent recruiters.": "Para empresas, agências e recrutadores independentes.",
  "From public application to private recruiter workflow.": "Da candidatura pública ao fluxo privado do recrutador.",
  "How Aptelys works": "Como a Aptelys funciona",
  "Live ATS workspace": "\u00c1rea ATS ao vivo",
  "Looking for open roles?": "Procurando vagas abertas?",
  "New company?": "Empresa nova?",
  "Once confirmed, this device stays signed in until you sign out.": "Depois de confirmado, este dispositivo permanece conectado até você sair.",
  "Open application": "Abrir candidatura",
  "Open roles for candidates.": "Vagas abertas para candidatos.",
  "Owner + recruiter setup": "Configura\u00e7\u00e3o de propriet\u00e1rio + recrutador",
  "Owner access": "Acesso de propriet\u00e1rio",
  "Owner and recruiter permissions": "Permiss\u00f5es de propriet\u00e1rio e recrutador",
  "At least 8 characters": "Pelo menos 8 caracteres",
  "Confirm password": "Confirmar senha",
  "Create new password": "Criar nova senha",
  "Existing sessions revoked": "Sess\u00f5es antigas revogadas",
  "New password": "Nova senha",
  "One-time secure link": "Link seguro de uso \u00fanico",
  "Open the secure link from your recovery email to reset your password.": "Abra o link seguro do email de recupera\u00e7\u00e3o para redefinir sua senha.",
  "Password reset": "Redefini\u00e7\u00e3o de senha",
  "Password must have at least 8 characters.": "A senha deve ter pelo menos 8 caracteres.",
  "Password updated. Sign in with your new password.": "Senha atualizada. Entre com sua nova senha.",
  "Passwords do not match.": "As senhas n\u00e3o conferem.",
  "Paste token or status URL": "Cole o token ou URL de status",
  "Paste your token or full status link.": "Cole seu token ou link completo de status.",
  "Persistent trusted-device login": "Login persistente em dispositivo confiável",
  "Protected by Aptelys workspace sessions.": "Protegido por sess\u00f5es do espa\u00e7o Aptelys.",
  "Public candidate application flow": "Fluxo público de candidatura",
  "Publish roles": "Publicar vagas",
  "Budgeting": "Or\u00e7amento",
  "Business Administration": "Administra\u00e7\u00e3o de Empresas",
  "Care": "Atendimento",
  "Clinic Coordinator": "Coordenador de Cl\u00ednica",
  "Coordinate daily workflows": "Coordenar fluxos di\u00e1rios",
  "Customer service": "Atendimento ao cliente",
  "Customer service, scheduling, Excel": "Atendimento ao cliente, agendamento, Excel",
  "Finance Analyst": "Analista Financeiro",
  "Hybrid Sao Paulo": "H\u00edbrido S\u00e3o Paulo",
  "Leadership": "Lideran\u00e7a",
  "Logistics": "Log\u00edstica",
  "Negotiation": "Negocia\u00e7\u00e3o",
  Operations: "Opera\u00e7\u00f5es",
  "Operations Coordinator": "Coordenador de Opera\u00e7\u00f5es",
  "Operations Coordinator - Hybrid Sao Paulo": "Coordenador de Opera\u00e7\u00f5es - H\u00edbrido S\u00e3o Paulo",
  "Operations Manager": "Gerente de Opera\u00e7\u00f5es",
  "Reporting": "Relat\u00f3rios",
  "Sales Account Executive": "Executivo de Vendas",
  "Support hiring managers": "Apoiar gestores da vaga",
  "Track operational KPIs": "Acompanhar KPIs operacionais",
  "Ready to operate": "Pronto para operar",
  "Repeat your new password": "Repita sua nova senha",
  "Request a new recovery email to receive a fresh secure link.": "Solicite um novo email de recupera\u00e7\u00e3o para receber um link seguro atualizado.",
  "Request new recovery link": "Solicitar novo link de recupera\u00e7\u00e3o",
  "Recruiter workspace": "\u00c1rea do recrutador",
  "Recruiters schedule interviews, automate emails, and monitor hiring performance.": "Recrutadores agendam entrevistas, automatizam e-mails e monitoram a performance de contrata\u00e7\u00e3o.",
  "Review with AI": "Revisar com IA",
  "Reset password": "Redefinir senha",
  "Secure recovery required.": "Recupera\u00e7\u00e3o segura obrigat\u00f3ria.",
  "Security checkpoint": "Ponto de verificação de segurança",
  "Senior Product Engineer": "Engenheiro de Produto Sênior",
  "Set a new password for your recruiting workspace.": "Defina uma nova senha para seu espa\u00e7o de recrutamento.",
  "Start again with your email and password to continue into Aptelys.": "Comece novamente com email e senha para continuar na Aptelys.",
  "Start with a workspace or review public opportunities.": "Comece com um espa\u00e7o ou veja oportunidades p\u00fablicas.",
  "Status token": "Token de status",
  "Aptelys helps recruiters create workspaces, publish jobs, parse resumes, rank candidates, schedule interviews, automate communication, and understand hiring performance from one polished ATS.": "A Aptelys ajuda recrutadores a criar espa\u00e7os, publicar vagas, analisar curr\u00edculos, ranquear candidatos, agendar entrevistas, automatizar comunica\u00e7\u00e3o e entender a performance de contrata\u00e7\u00e3o em um ATS polido.",
  "Aptelys workspace access stays active on trusted devices until sign out.": "O acesso ao espa\u00e7o Aptelys permanece ativo em dispositivos confi\u00e1veis at\u00e9 voc\u00ea sair.",
  "The first user becomes the workspace owner and can immediately create jobs, parse resumes, rank candidates, and invite recruiters.": "O primeiro usu\u00e1rio vira propriet\u00e1rio do espa\u00e7o e pode criar vagas, analisar curr\u00edculos, ranquear candidatos e convidar recrutadores imediatamente.",
  "This email already has an account. Sign in or use an invitation link.": "Este email já tem uma conta. Entre ou use um link de convite.",
  "This recovery link is expired or has already been used.": "Este link de recupera\u00e7\u00e3o expirou ou j\u00e1 foi usado.",
  "That code is not valid. Check your email and try again.": "Esse c\u00f3digo n\u00e3o \u00e9 v\u00e1lido. Confira seu email e tente novamente.",
  "The code expires in 10 minutes and can be used only once.": "O c\u00f3digo expira em 10 minutos e s\u00f3 pode ser usado uma vez.",
  "This verification code expired. Start the sign-in again to receive a new code.": "Este c\u00f3digo de verifica\u00e7\u00e3o expirou. Inicie o login novamente para receber um novo c\u00f3digo.",
  "Too many incorrect attempts. Start the sign-in again to receive a new code.": "Muitas tentativas incorretas. Inicie o login novamente para receber um novo c\u00f3digo.",
  "The workspace owner receives a 6-digit security code by email.": "O propriet\u00e1rio do espa\u00e7o recebe um c\u00f3digo de seguran\u00e7a de 6 d\u00edgitos por email.",
  "Track application": "Acompanhar candidatura",
  "Trusted device session": "Sessão em dispositivo confiável",
  "Use sign out to remove access from this browser.": "Use sair para remover o acesso deste navegador.",
  "Use your secure application link or token to follow the process timeline.": "Use seu link seguro de candidatura ou token para acompanhar a linha do tempo do processo.",
  "Use your work email as the primary identity check.": "Use seu email de trabalho como verificação principal de identidade.",
  "Verification expired": "Verificação expirada",
  "Verification code": "C\u00f3digo de verifica\u00e7\u00e3o",
  "Verify and continue": "Verificar e continuar",
  "Verify workspace owner": "Verificar propriet\u00e1rio do espa\u00e7o",
  "Verify your login": "Verificar seu login",
  "View available jobs": "Ver vagas disponíveis",
  "View open roles": "Ver vagas abertas",
  "View roles": "Ver vagas",
  "Work email": "Email de trabalho",
  "Your name": "Seu nome",
  "0 min": "0 min",
  "15 min": "15 min",
  "30 min": "30 min",
  "45 min": "45 min",
  "60 min": "60 min",
  "70-84 review": "70-84 revisar",
  "85+ strong": "85+ forte",
  "90 min": "90 min",
  Account: "Conta",
  Active: "Ativo",
  "Active intake": "Entrada ativa",
  "Active jobs": "Vagas ativas",
  "Active rules": "Regras ativas",
  "Active users": "Usuários ativos",
  "Add candidate": "Adicionar candidato",
  "Add candidates or parse resumes before ranking a role.": "Adicione candidatos ou analise currículos antes de ranquear uma vaga.",
  "Add note": "Adicionar nota",
  "Add recruiter context, screening notes, or next steps.": "Adicione contexto do recrutador, notas de triagem ou próximos passos.",
  "Add user": "Adicionar usuário",
  Added: "Adicionado",
  "Adjust filters or wait for new public applications.": "Ajuste os filtros ou aguarde novas candidaturas públicas.",
  Admins: "Admins",
  "Analyzing resume": "Analisando currículo",
  "AI Product Engineer": "Engenheiro de Produto IA",
  "AI recruiting operations with real access control.": "Operações de recrutamento com IA e controle de acesso real.",
  "AI resume parser": "Parser de currículo com IA",
  "AI strengths": "Pontos fortes da IA",
  "All job actions are scoped by organizationId.": "Todas as ações de vaga são isoladas por organizationId.",
  "All jobs": "Todas as vagas",
  "All sources": "Todas as fontes",
  "All stages": "Todas as etapas",
  "Any score": "Qualquer score",
  "Any stage": "Qualquer etapa",
  "Any status": "Qualquer status",
  "Application closed": "Candidatura encerrada",
  "Application details": "Detalhes da candidatura",
  "Application moved to screening.": "Candidatura movida para triagem.",
  "Application received": "Candidatura recebida",
  "Application received.": "Candidatura recebida.",
  "Application rejected and email queued.": "Candidatura rejeitada e email enfileirado.",
  "Application rejected and email sent.": "Candidatura rejeitada e email enviado.",
  "Application rejected and rejection email queued.": "Candidatura rejeitada e email de rejeição enfileirado.",
  "Application rejected and rejection email sent.": "Candidatura rejeitada e email de rejeição enviado.",
  "Application rejected without email.": "Candidatura rejeitada sem email.",
  "Application rejected, but email delivery failed.": "Candidatura rejeitada, mas a entrega do email falhou.",
  "Application rejected, but the email delivery failed.": "Candidatura rejeitada, mas a entrega do email falhou.",
  "Application status": "Status da candidatura",
  "Applications Inbox": "Caixa de candidaturas",
  Applied: "Aplicado",
  "Apply for this role": "Candidatar-se a esta vaga",
  "Apply now": "Candidatar-se",
  "Apply parsed data to candidate": "Aplicar dados extraídos ao candidato",
  "Apply selected": "Aplicar selecionados",
  "Apply selected data": "Aplicar dados selecionados",
  "Apply to job": "Aplicar à vaga",
  Apps: "Candidaturas",
  Archive: "Arquivar",
  "Assignable users": "Usuários atribuíveis",
  "Attach for review": "Anexar para revisão",
  "Attach resume": "Anexar currículo",
  "Audit trail": "Trilha de auditoria",
  Automation: "Automação",
  "Automation rule updated.": "Regra de automação atualizada.",
  "Automation rules": "Regras de automação",
  Automations: "Automações",
  Availability: "Disponibilidade",
  "Availability settings updated.": "Configurações de disponibilidade atualizadas.",
  "Available times": "Horários disponíveis",
  Avg: "Média",
  "Avg match score": "Score médio de match",
  "Avg score": "Score médio",
  "Avg. match score": "Score médio de match",
  "Backend Platform Engineer": "Engenheiro de Plataforma Backend",
  "Below 70": "Abaixo de 70",
  "Bulk actions": "Ações em massa",
  "Calendar cancelled": "Calendário cancelado",
  "Calendar event": "Evento de calendário",
  "Calendar failed": "Falha no calendário",
  "Calendar sync": "Sincronização de calendário",
  Calendars: "Calendários",
  Cancelled: "Cancelado",
  "Cancelled/no-show": "Cancelado/não compareceu",
  Candidate: "Candidato",
  "Candidate created": "Candidato criado",
  "Candidate Detail": "Detalhe do candidato",
  "Candidate profile": "Perfil do candidato",
  "Candidate ranking saved to the ATS pipeline.": "Ranking do candidato salvo no pipeline ATS.",
  "Candidate status": "Status do candidato",
  "Candidate, skills, education, resume document, and applications persist separately.": "Candidato, competências, educação, currículo e candidaturas são persistidos separadamente.",
  Candidates: "Candidatos",
  "Candidates added to this role will appear in this pipeline.": "Candidatos adicionados a esta vaga aparecerão neste pipeline.",
  Careers: "Carreiras",
  "Careers Page": "Página de carreiras",
  "Careers page": "Página de carreiras",
  "Choose your interview time": "Escolha o horário da entrevista",
  "Clear search": "Limpar busca",
  "Close navigation": "Fechar navegação",
  Closed: "Fechado",
  Completed: "Concluído",
  Confirmation: "Confirmação",
  "Confirmation email": "Email de confirmação",
  "Confirmation needs attention": "Confirmação precisa de atenção",
  "Confirmation pending": "Confirmação pendente",
  "Confirmation queue": "Fila de confirmação",
  "Confirmation queued": "Confirmação enfileirada",
  "Confirmation sent": "Confirmação enviada",
  Confirmed: "Confirmado",
  "Connect Google Calendar": "Conectar Google Calendar",
  Contact: "Contato",
  Contract: "Contrato",
  "Conversion rates": "Taxas de conversão",
  "Create job": "Criar vaga",
  "Create a job to start your first pipeline": "Crie uma vaga para iniciar seu primeiro pipeline",
  "Create first job": "Criar primeira vaga",
  "Create rejection template": "Criar template de rejeição",
  "Create rule": "Criar regra",
  "Create schedule link": "Criar link de agenda",
  "Create scheduling link": "Criar link de agendamento",
  "Create template": "Criar template",
  "Create your first job to generate the ATS stages and start moving candidates through the workflow.": "Crie sua primeira vaga para gerar as etapas do ATS e mover candidatos pelo fluxo.",
  "Create your first role to start building the hiring pipeline.": "Crie a primeira vaga para começar a montar o pipeline de contratação.",
  "Create, review, pause, close, or archive hiring roles.": "Crie, revise, pause, feche ou arquive vagas.",
  Created: "Criado",
  "Created by": "Criado por",
  "CRM readiness": "Prontidão do CRM",
  "Current status": "Status atual",
  "Current:": "Atual:",
  Dashboard: "Painel",
  "Data boundary": "Limite de dados",
  "Data Product Engineer": "Engenheiro de Produto de Dados",
  "Delivery provider": "Provider de entrega",
  "Demo owner": "Owner demo",
  Department: "Departamento",
  "Describe the role, seniority, team, and hiring goals.": "Descreva a vaga, senioridade, time e objetivos da contratação.",
  Disabled: "Desativado",
  Disconnect: "Desconectar",
  Download: "Baixar",
  Draft: "Rascunho",
  "Edit interview": "Editar entrevista",
  "Edit profile": "Editar perfil",
  Education: "Educação",
  Email: "Email",
  "Email delivery": "Entrega de email",
  "Email delivery failed. Check provider settings and message details.": "Falha na entrega do email. Verifique as configurações do provider e os detalhes da mensagem.",
  "Email history": "Histórico de emails",
  "Email issues": "Problemas de email",
  "Email queue": "Fila de email",
  "Email queued in the outbox. Configure Resend to send it.": "Email enfileirado na caixa de saída. Configure o Resend para enviá-lo.",
  "Email sent through the configured provider.": "Email enviado pelo provider configurado.",
  "Email template saved.": "Template de email salvo.",
  "Email, password, or workspace access is invalid.": "Email, senha ou acesso ao workspace inválido.",
  Emails: "E-mails",
  Engineering: "Engenharia",
  "Enter workspace": "Entrar no workspace",
  Enterprise: "Empresarial",
  Experience: "Experiência",
  "Experience and education": "Experiência e educação",
  "Extracting PDF text locally": "Extraindo texto do PDF localmente",
  Failed: "Falhou",
  "Fallback resume text": "Texto de fallback do currículo",
  "Failed extraction": "Extração falhou",
  Field: "Área",
  Filter: "Filtrar",
  Final: "Final",
  Format: "Formato",
  Free: "Grátis",
  From: "De",
  "Frontend Engineer": "Engenheiro Frontend",
  "Full Stack Developer": "Desenvolvedor Full Stack",
  "Full Stack Engineer": "Engenheiro Full Stack",
  "Full time": "Tempo integral",
  Gaps: "Gaps",
  "Google Calendar connected.": "Google Calendar conectado.",
  "Google Calendar connection failed state validation.": "Conexão com Google Calendar falhou na validação de estado.",
  "Google Calendar disconnected.": "Google Calendar desconectado.",
  "Google Calendar event cancelled.": "Evento do Google Calendar cancelado.",
  "Google Calendar event updated.": "Evento do Google Calendar atualizado.",
  "Google Calendar OAuth is missing client configuration.": "OAuth do Google Calendar está sem configuração de client.",
  "Hire rate": "Taxa de contratação",
  "Hired": "Contratado",
  "Hiring Analytics": "Analytics de contratação",
  "Hiring manager": "Gestor da vaga",
  "Hiring manager conversation": "Conversa com gestor da vaga",
  "Hiring team": "Time de contratação",
  "Hiring teams": "Times de contratação",
  "Hiring timeline": "Linha do tempo da contratação",
  Hybrid: "Híbrido",
  Inbound: "Entrada",
  Indeed: "Indeed",
  "Integration status": "Status das integrações",
  Internal: "Interno",
  Internship: "Estágio",
  "Interview calendar": "Calendário de entrevistas",
  "Interview confirmation": "Confirmação de entrevista",
  "Interview details": "Detalhes da entrevista",
  "Interview rate": "Taxa de entrevista",
  "Interview Schedule": "Agenda de entrevistas",
  "Interview scheduled": "Entrevista agendada",
  "Interview scheduled and candidate moved into the interview stage.": "Entrevista agendada e candidato movido para a etapa de entrevista.",
  "Interview scheduled without calendar sync.": "Entrevista agendada sem sincronização de calendário.",
  "Interview scheduled, but Google Calendar sync failed.": "Entrevista agendada, mas a sincronização com Google Calendar falhou.",
  "Interview scheduled. Assign an organizer to sync with Google Calendar.": "Entrevista agendada. Atribua um organizador para sincronizar com o Google Calendar.",
  "Interview scheduled. Connect Google Calendar to sync future events.": "Entrevista agendada. Conecte o Google Calendar para sincronizar próximos eventos.",
  "Interview stage": "Etapa de entrevista",
  "Interview status updated, but Google Calendar cancellation failed.": "Status da entrevista atualizado, mas o cancelamento no Google Calendar falhou.",
  "Interview status updated.": "Status da entrevista atualizado.",
  "Interview synced to Google Calendar.": "Entrevista sincronizada com o Google Calendar.",
  "Interview updated, but Google Calendar sync failed.": "Entrevista atualizada, mas a sincronização com Google Calendar falhou.",
  "Interview updated. The Google Calendar event was already removed.": "Entrevista atualizada. O evento do Google Calendar já havia sido removido.",
  "Interview-ready": "Pronto para entrevista",
  Interviews: "Entrevistas",
  Invited: "Convidado",
  Issues: "Problemas",
  Job: "Vaga",
  "Job status": "Status da vaga",
  Jobs: "Vagas",
  "Join meeting": "Entrar na reunião",
  "Leave empty for Google Meet": "Deixe vazio para Google Meet",
  Location: "Localização",
  "Machine Learning Product Engineer": "Engenheiro de Produto de Machine Learning",
  "Managed jobs": "Vagas gerenciadas",
  Manager: "Gestor",
  Manual: "Manual",
  "Manual review": "Revisão manual",
  "Manual review queue": "Fila de revisão manual",
  Matching: "Matching",
  "Matching engine": "Motor de matching",
  "Meeting link": "Link da reunião",
  Mode: "Modo",
  "More job actions": "Mais ações de vaga",
  "Move to screening": "Mover para triagem",
  "Moved to stage": "Movido para etapa",
  "Name and email are required.": "Nome e email são obrigatórios.",
  "Needs attention": "Precisa de atenção",
  "Needs review": "Precisa de revisão",
  "New job": "Nova vaga",
  "New parsing exceptions will appear here.": "Novas exceções de análise aparecerão aqui.",
  "New today": "Novas hoje",
  "Next unlock": "Próximo desbloqueio",
  "No active jobs available.": "Nenhuma vaga ativa disponível.",
  "No active job pipeline yet.": "Nenhum pipeline de vaga ativo ainda.",
  "No activity yet.": "Nenhuma atividade ainda.",
  "No applications found": "Nenhuma candidatura encontrada",
  "No applications yet": "Nenhuma candidatura ainda",
  "No applications yet.": "Nenhuma candidatura ainda.",
  "No audit events yet.": "Nenhum evento de auditoria ainda.",
  "No candidate selected.": "Nenhum candidato selecionado.",
  "No candidates yet": "Nenhum candidato ainda",
  "No education or experience details yet.": "Nenhum detalhe de educação ou experiência ainda.",
  "No email template": "Nenhum template de email",
  "No emails yet.": "Nenhum email ainda.",
  "No hires closed yet": "Nenhuma contratação fechada ainda",
  "No interviews yet": "Nenhuma entrevista ainda",
  "No interviews yet.": "Nenhuma entrevista ainda.",
  "No jobs match this search.": "Nenhuma vaga corresponde à busca.",
  "No jobs yet": "Nenhuma vaga ainda",
  "No major gaps detected.": "Nenhum gap importante detectado.",
  "No matching candidates in this stage.": "Nenhum candidato encontrado nesta etapa.",
  "No messages yet": "Nenhuma mensagem ainda",
  "No notes yet.": "Nenhuma nota ainda.",
  "No open roles": "Nenhuma vaga aberta",
  "No open slots": "Nenhum horário disponível",
  "No resumes stored yet.": "Nenhum currículo armazenado ainda.",
  "No resumes waiting review": "Nenhum currículo aguardando revisão",
  "No show": "Não compareceu",
  "No skills": "Sem competências",
  "No skills yet": "Sem competências ainda",
  "No skills yet.": "Sem competências ainda.",
  Notes: "Notas",
  "Offer created": "Oferta criada",
  "Offer rate": "Taxa de oferta",
  "Offer stage": "Etapa de oferta",
  Offers: "Ofertas",
  "Only add to database": "Apenas adicionar ao banco",
  Onsite: "Presencial",
  Open: "Aberta",
  "Open Jobs": "Vagas abertas",
  "Open jobs actions": "Abrir ações de vagas",
  "Open navigation": "Abrir navegação",
  "Open pipeline": "Abrir pipeline",
  "Open profile": "Abrir perfil",
  "Open requisitions": "Requisições abertas",
  "Open roles": "Vagas abertas",
  "OpenAI resume AI": "IA de currículos OpenAI",
  Openings: "Vagas abertas",
  "Optional. Text PDFs are parsed locally; paste text here for scanned or image-only PDFs.": "Opcional. PDFs com texto são analisados localmente; cole o texto aqui para PDFs escaneados ou apenas imagem.",
  Organization: "Organização",
  "Organization settings": "Configurações da organização",
  "Organization settings updated.": "Configurações da organização atualizadas.",
  Organizer: "Organizador",
  Other: "Outro",
  Outbox: "Caixa de saída",
  Owner: "Owner",
  "Parse resume": "Analisar currículo",
  Parsed: "Analisado",
  "Parsed email already belongs to another candidate in this organization.": "O email extraído já pertence a outro candidato desta organização.",
  "Parsed resume data applied to the candidate profile": "Dados extraídos do currículo aplicados ao perfil do candidato",
  "Parsed resumes": "Currículos analisados",
  "Parsed:": "Analisado:",
  "Part time": "Meio período",
  Password: "Senha",
  "Paste extracted resume text here for now. The next module will replace this with real file upload and AI parsing.": "Cole o texto extraído do currículo por enquanto. O próximo módulo substituirá isso por upload real de arquivo e análise com IA.",
  "Paste resume text here when uploading a text-free PDF locally or when you want a quick reprocess.": "Cole o texto do currículo aqui ao enviar um PDF sem texto localmente ou quando quiser reprocessar rapidamente.",
  "Paste resume text if you do not upload a file.": "Cole o texto do currículo se não enviar um arquivo.",
  Paused: "Pausado",
  Pending: "Pendente",
  "People Operations Specialist": "Especialista de People Operations",
  "Permission matrix": "Matriz de permissões",
  Persistence: "Persistência",
  "Phone screen": "Triagem por telefone",
  Pipeline: "Pipeline",
  "Pipeline funnel": "Funil do pipeline",
  "Pipeline sync": "Sincronização do pipeline",
  "Pipeline time": "Tempo no pipeline",
  "Pipeline volume and score health by role": "Volume do pipeline e saúde do score por vaga",
  "Please ask the recruiting team to extend the scheduling window.": "Peça ao time de recrutamento para ampliar a janela de agendamento.",
  "Please check back later for new opportunities.": "Volte mais tarde para novas oportunidades.",
  Pro: "Pro",
  Profile: "Perfil",
  "Profile update": "Atualização de perfil",
  "Profiles, parsed resume state, skills, and active applications.": "Perfis, estado do currículo analisado, competências e candidaturas ativas.",
  "Protect candidates, jobs, automation, analytics, and admin settings behind organization roles.": "Proteja candidatos, vagas, automação, analytics e configurações administrativas por papéis da organização.",
  Provider: "Provider",
  "Public intake": "Entrada pública",
  "Public page": "Página pública",
  Published: "Publicado",
  "Queue email": "Enfileirar email",
  "Queue the first template email from an active application.": "Enfileire o primeiro email de template a partir de uma candidatura ativa.",
  Queued: "Enfileirado",
  "Queued emails": "Emails enfileirados",
  "Queued, sent, and event-driven candidate messages.": "Mensagens de candidatos enfileiradas, enviadas e disparadas por eventos.",
  "Rank candidates": "Ranquear candidatos",
  "Rank candidates and schedule the first interview from an active application.": "Ranqueie candidatos e agende a primeira entrevista a partir de uma candidatura ativa.",
  Ranked: "Ranqueado",
  "Ranked shortlist": "Shortlist ranqueada",
  "Raw preview": "Prévia bruta",
  "Real upload plus OpenAI parsing can write into the same tables.": "Upload real mais análise com OpenAI podem gravar nas mesmas tabelas.",
  "Recent activity": "Atividade recente",
  Recipient: "Destinatário",
  Recruiter: "Recrutador",
  "Recruiter screen": "Triagem com recrutador",
  "Recruiter review": "Revisão do recrutador",
  "Recruiting Operations Lead": "Líder de Operações de Recrutamento",
  "Recruiting Operations Manager": "Gerente de Operações de Recrutamento",
  "Recruiting Coordinator": "Coordenador de Recrutamento",
  "Recruiting": "Recrutamento",
  "Referral": "Indicação",
  "Refresh invite": "Reenviar convite",
  Reject: "Rejeitar",
  "Reject candidate": "Rejeitar candidato",
  "Reject with email": "Rejeitar com email",
  Rejected: "Rejeitado",
  "Rejection sent": "Rejeição enviada",
  "Rejection template": "Template de rejeição",
  "Rejection templates": "Templates de rejeição",
  Remote: "Remoto",
  "Remote LATAM": "Remoto LATAM",
  "Replace skills": "Substituir competências",
  Requirements: "Requisitos",
  Responsibilities: "Responsabilidades",
  Resume: "Currículo",
  "Resume file": "Arquivo do currículo",
  "Resume file must be 10 MB or smaller.": "O arquivo do currículo deve ter 10 MB ou menos.",
  "Resume file name": "Nome do arquivo do currículo",
  "Resume is too large. Upload a file under 10 MB.": "O currículo é grande demais. Envie um arquivo com menos de 10 MB.",
  "Resume marked reviewed.": "Currículo marcado como revisado.",
  "Resume parse preview": "Prévia da análise do currículo",
  "Resume parsed and saved to the candidate CRM.": "Currículo analisado e salvo no CRM de candidatos.",
  "Resume parser": "Parser de currículo",
  "Resume parser queue": "Fila do parser de currículos",
  "Resume review": "Revisão de currículo",
  "Resume saved for review. No structured data was extracted automatically.": "Currículo salvo para revisão. Nenhum dado estruturado foi extraído automaticamente.",
  "Resume saved for review. Configure OPENAI_API_KEY to enable full AI parsing for PDFs.": "Currículo salvo para revisão. Configure OPENAI_API_KEY para habilitar análise completa com IA para PDFs.",
  "Resume uploaded for manual review. No structured data was extracted automatically.": "Currículo enviado para revisão manual. Nenhum dado estruturado foi extraído automaticamente.",
  "Resume uploaded, but OpenAI parsing failed. Review the file manually or retry parsing.": "Currículo enviado, mas a análise com OpenAI falhou. Revise o arquivo manualmente ou tente analisar novamente.",
  "Resume text": "Texto do currículo",
  Review: "Revisão",
  "Review extracted data": "Revisar dados extraídos",
  "Review notes": "Notas de revisão",
  Reviewed: "Revisado",
  Role: "Vaga",
  "Role brief": "Resumo da vaga",
  "Role history and match explanations": "Histórico por vaga e explicações de match",
  "Role performance": "Performance por vaga",
  "Role queue": "Fila de vagas",
  "Role requirements": "Requisitos da vaga",
  Roles: "Papéis",
  "S3-compatible storage": "Storage compatível com S3",
  Salary: "Salário",
  "Salary max": "Salário máximo",
  "Salary min": "Salário mínimo",
  Save: "Salvar",
  "Save access": "Salvar acesso",
  "Save availability": "Salvar disponibilidade",
  "Save candidate": "Salvar candidato",
  "Save note": "Salvar nota",
  "Save profile": "Salvar perfil",
  "Save rule": "Salvar regra",
  "Save settings": "Salvar configurações",
  "Save status": "Salvar status",
  "Save template": "Salvar template",
  Schedule: "Agendar",
  "Schedule and status changes are recorded as organization-scoped events.": "Agendamentos e mudanças de status são registrados como eventos isolados por organização.",
  "Schedule interview": "Agendar entrevista",
  Scheduled: "Agendado",
  "Scheduling an interview moves the application into the Interview stage.": "Agendar uma entrevista move a candidatura para a etapa de Entrevista.",
  "Scheduling link": "Link de agendamento",
  "Scheduling link expired": "Link de agendamento expirado",
  "Scheduling link not found": "Link de agendamento não encontrado",
  "Scheduling unavailable": "Agendamento indisponível",
  Score: "Score",
  "Score updated": "Score atualizado",
  "Scores write to Application.matchScore and feed the ATS pipeline.": "Scores são gravados em Application.matchScore e alimentam o pipeline ATS.",
  "Search Engineer": "Engenheiro de Busca",
  "Search view placeholder": "Buscar na visualização",
  Screening: "Triagem",
  "Secure workspace": "Workspace seguro",
  Select: "Selecionar",
  "Select application": "Selecionar candidatura",
  "Select at least one application.": "Selecione pelo menos uma candidatura.",
  "Select at least one parsed field to apply.": "Selecione pelo menos um campo extraído para aplicar.",
  "Select candidate and role": "Selecionar candidato e vaga",
  "Select rejection template": "Selecionar template de rejeição",
  "Select template": "Selecionar template",
  "Selected file:": "Arquivo selecionado:",
  "Selected applications do not have resumes to review.": "As candidaturas selecionadas não têm currículos para revisar.",
  "Selected fields refresh profile data and matching scores.": "Os campos selecionados atualizam dados do perfil e scores de matching.",
  "Selected role": "Vaga selecionada",
  "Self-scheduling": "Autoagendamento",
  "Self-scheduling link created for the application.": "Link de autoagendamento criado para a candidatura.",
  "Self-scheduling link created.": "Link de autoagendamento criado.",
  "Send interview confirmation": "Enviar confirmação de entrevista",
  "Send now": "Enviar agora",
  "Senior Full Stack Engineer": "Engenheiro Full Stack Sênior",
  "Senior Full Stack Engineer - Remote LATAM": "Engenheiro Full Stack Sênior - Remoto LATAM",
  "Senior Recruiter": "Recrutador Sênior",
  "Senior Software Engineer": "Engenheiro de Software Sênior",
  Sent: "Enviado",
  "Set only when activating access": "Defina apenas ao ativar o acesso",
  Settings: "Configurações",
  "Share context, availability, or why this role fits.": "Compartilhe contexto, disponibilidade ou por que esta vaga faz sentido.",
  "Short recruiter-facing profile summary.": "Resumo curto para o recrutador.",
  "Sign in": "Entrar",
  "Site navigation": "Navegação do site",
  Skills: "Competências",
  Source: "Fonte",
  "Source quality": "Qualidade por fonte",
  Stage: "Etapa",
  "Stage changed": "Etapa alterada",
  Stages: "Etapas",
  Status: "Status",
  "Staff Full Stack Engineer": "Engenheiro Full Stack Staff",
  Strengths: "Pontos fortes",
  "Strong matches": "Matches fortes",
  "Structured profile": "Perfil estruturado",
  "Submit application": "Enviar candidatura",
  "Talent database": "Banco de talentos",
  "Talent pool": "Banco de talentos",
  Target: "Pretensão",
  "Target salary": "Pretensão salarial",
  Team: "Time",
  Technical: "Técnica",
  "Technical architecture interview": "Entrevista de arquitetura técnica",
  "Technical screen": "Entrevista técnica",
  Template: "Template",
  Templates: "Templates",
  "Tenant scope": "Escopo do tenant",
  "The recruiting team can still review this application.": "O time de recrutamento ainda pode revisar esta candidatura.",
  "The recruiting team has your selected time. You will receive the details by email if automation is configured.": "O time de recrutamento recebeu o horário escolhido. Você receberá os detalhes por email se a automação estiver configurada.",
  "This application does not have a resume yet.": "Esta candidatura ainda não tem currículo.",
  "This job is not accepting applications anymore.": "Esta vaga não está mais aceitando candidaturas.",
  "This job is not available anymore.": "Esta vaga não está mais disponível.",
  "This resume does not have structured parsed data to apply.": "Este currículo não possui dados estruturados extraídos para aplicar.",
  Title: "Título",
  Today: "Hoje",
  "Top AI Matches": "Principais matches por IA",
  "Top score": "Maior score",
  "Total jobs": "Total de vagas",
  Type: "Tipo",
  "UI Engineer": "Engenheiro de UI",
  Unassigned: "Não atribuído",
  "Upcoming and completed interviews across active requisitions.": "Entrevistas futuras e concluídas nas requisições ativas.",
  "Update interview": "Atualizar entrevista",
  Updated: "Atualizado",
  "Upload a resume file or paste resume text.": "Envie um arquivo de currículo ou cole o texto do currículo.",
  "Upload a resume or add a candidate to start reviewing profiles here.": "Envie um currículo ou adicione um candidato para começar a revisar perfis aqui.",
  "Upload resume": "Enviar currículo",
  User: "Usuário",
  Users: "Usuários",
  Variables: "Variáveis",
  View: "Ver",
  "View role": "Ver vaga",
  Viewer: "Visualizador",
  "We sent a confirmation email when a delivery provider is configured. This page stays available for status updates.": "Enviamos um email de confirmação quando há um provider de entrega configurado. Esta página fica disponível para atualizações de status.",
  "Webhook endpoint": "Endpoint de webhook",
  Workflow: "Workflow",
  "Work mode": "Modelo de trabalho",
  "Workspace invite refreshed.": "Convite do workspace atualizado.",
  "Workspace member updated.": "Membro do workspace atualizado.",
  "Workspace readiness": "Prontidão do workspace",
  "Workspace settings updated.": "Configurações do workspace atualizadas.",
  "Workspace summary": "Resumo do workspace",
  "Workspace users": "Usuários do workspace",
  "Your availability": "Sua disponibilidade",
  "Your interview is scheduled.": "Sua entrevista está agendada.",
  "Your profile was added to the hiring pipeline. The recruiting team can now review your resume.": "Seu perfil foi adicionado ao pipeline de contratação. O time de recrutamento já pode revisar seu currículo.",
  "Mon": "Seg",
  "Tue": "Ter",
  "Wed": "Qua",
  "Thu": "Qui",
  "Fri": "Sex",
  "Sat": "Sáb",
  "Sun": "Dom",
  "2 weeks": "2 semanas",
  "30 days": "30 dias",
  "45 days": "45 dias",
  Immediate: "Imediato",
  "Default (30 min)": "Padrão (30 min)",
  "Default (45 min)": "Padrão (45 min)",
  "Phone Screen": "Triagem por telefone",
  "Hiring Manager": "Gestor da vaga",
  Analytics: "Análises",
  Interview: "Entrevista",
  Offer: "Oferta",
  Parse: "Analisar",
  Rank: "Ranquear",
  "Full Time": "Tempo integral",
  "Remote Brazil": "Remoto Brasil",
  "No email": "Sem email",
  "No phone": "Sem telefone",
  "Not provided": "Não informado",
  "Pending parse": "Análise pendente",
  Attention: "Atenção",
  People: "Pessoas",
  "AI-ready": "Pronto para IA",
  "Next step for": "Próximo passo para",
  "avg in stage": "média na etapa",
  "candidates in process": "candidatos em processo",
  "AI Platform": "Plataforma IA",
  "Already scheduled": "Já agendado",
  "Application Received": "Candidatura recebida",
  "Awaiting provider": "Aguardando provider",
  Bounced: "Devolvido",
  Calendar: "Calendário",
  "Calendar Sync": "Sincronização de calendário",
  Clear: "Em dia",
  "Computer Science": "Ciência da Computação",
  "Current pipeline": "Pipeline atual",
  "Data missing": "Dados ausentes",
  Delivered: "Entregue",
  "Direct ATS": "ATS direto",
  "Email Automation": "Automação de email",
  Healthy: "Saudável",
  "Hybrid Lisbon": "Híbrido Lisboa",
  "INTERVIEW_SCHEDULED": "Entrevista agendada",
  "Moved To Stage": "Movido para etapa",
  "MOVED_TO_STAGE": "Movido para etapa",
  NAME: "Nome",
  "Offer Created": "Oferta criada",
  "OFFER_CREATED": "Oferta criada",
  PLAN: "Plano",
  Ready: "Pronto",
  "REJECTION_SENT": "Rejeição enviada",
  SLUG: "Slug",
  Synced: "Sincronizado",
  TIMEZONE: "Fuso horário",
  "Build integration-safe backend APIs": "Construir APIs backend seguras para integrações",
  "Build LLM-powered extraction, matching, ranking, and review experiences for recruiters using TypeScript, OpenAI APIs, embeddings, and product analytics.":
    "Construir experiências de extração, matching, ranking e revisão com LLM para recrutadores usando TypeScript, APIs OpenAI, embeddings e análises de produto.",
  "Design APIs, queueing, database performance, integration infrastructure, and background processing foundations for a recruiting automation platform.":
    "Desenhar APIs, filas, performance de banco, infraestrutura de integrações e bases de processamento em background para uma plataforma de automação de recrutamento.",
  "Design resilient APIs, server actions, and database models": "Desenhar APIs resilientes, server actions e modelos de banco de dados",
  "Evaluate candidate ranking quality and explainability": "Avaliar qualidade e explicabilidade do ranking de candidatos",
  "Failed syncs need reconnect or retry.": "Falhas de sincronização precisam de reconexão ou nova tentativa.",
  "Hi {{candidateName}}, thanks for applying to {{jobTitle}}. We received your resume and our team will review your profile soon.":
    "Olá {{candidateName}}, obrigado por se candidatar para {{jobTitle}}. Recebemos seu currículo e nosso time revisará seu perfil em breve.",
  "Hi {{candidateName}}, thank you for your time in the {{jobTitle}} process. We will not be moving forward at this stage, but we appreciate your interest.":
    "Olá {{candidateName}}, obrigado pelo seu tempo no processo de {{jobTitle}}. Não seguiremos em frente nesta etapa, mas agradecemos seu interesse.",
  "Hi {{candidateName}}, we are excited to discuss offer details and next steps with you.":
    "Olá {{candidateName}}, estamos animados para conversar sobre detalhes da oferta e próximos passos com você.",
  "Hi {{candidateName}}, your interview is confirmed for {{interviewTime}}. We are looking forward to speaking with you.":
    "Olá {{candidateName}}, sua entrevista está confirmada para {{interviewTime}}. Estamos ansiosos para conversar com você.",
  "Hi {{candidateName}}, your profile looks aligned with {{jobTitle}}. Please choose a time for a recruiter screen.":
    "Olá {{candidateName}}, seu perfil parece alinhado com {{jobTitle}}. Escolha um horário para uma triagem com recrutador.",
  "Lead recruiting operations, candidate communication workflows, ATS governance, funnel reporting, and hiring team enablement for a scaling SaaS company.":
    "Liderar operações de recrutamento, fluxos de comunicação com candidatos, governança do ATS, relatórios de funil e enablement dos times de contratação em uma SaaS em escala.",
  "Offer alignment call": "Alinhamento de oferta",
  "Own database performance and queue reliability": "Cuidar da performance do banco e da confiabilidade das filas",
  "Own end-to-end product delivery for an AI recruitment platform with React, Node.js, PostgreSQL, calendar integrations, and AI-assisted resume workflows.":
    "Conduzir entrega ponta a ponta de produto para uma plataforma de recrutamento com IA usando React, Node.js, PostgreSQL, integrações de calendário e fluxos de currículo assistidos por IA.",
  "Own pipeline hygiene, templates, SLAs, and reporting": "Cuidar da higiene do pipeline, templates, SLAs e relatórios",
  "Prepare background jobs for production hiring workflows": "Preparar jobs em background para fluxos de contratação em produção",
  "Prototype AI-assisted recruiter workflows": "Prototipar fluxos de recrutamento assistidos por IA",
  "Resume uploaded and waiting for OpenAI parsing. Add OPENAI_API_KEY to enable AI extraction.":
    "Currículo enviado e aguardando análise com OpenAI. Adicione OPENAI_API_KEY para habilitar extração com IA.",
  "OpenAI did not return structured resume data. Review manually or retry parsing.":
    "A OpenAI não retornou dados estruturados do currículo. Revise manualmente ou tente analisar novamente.",
  "OpenAI parsing failed. The resume was saved; check the parser model, billing, or retry.":
    "A análise com OpenAI falhou. O currículo foi salvo; verifique o modelo do parser, billing ou tente novamente.",
  "OPENAI_API_KEY is required to parse PDF content.": "OPENAI_API_KEY é necessária para analisar conteúdo de PDF.",
  "Detecting skills, experience, and education": "Detectando competências, experiência e formação",
  "Review failed or low-confidence parses before matching.": "Revise análises com falha ou baixa confiança antes do matching.",
  "Active rules send messages when candidates move stage, schedule interviews, or get rejected.":
    "Regras ativas enviam mensagens quando candidatos mudam de etapa, agendam entrevistas ou são rejeitados.",
  "Local parsing and matching fallback is active. Add OPENAI_API_KEY for live AI extraction.":
    "Fallback local de análise e matching está ativo. Adicione OPENAI_API_KEY para extração real com IA.",
  "Local PDF parser could not extract structured resume data.": "O parser local de PDF não conseguiu extrair dados estruturados do currículo.",
  "Local PDF text extraction failed. Paste resume text for manual fallback parsing.":
    "A extração local de texto do PDF falhou. Cole o texto do currículo para usar o parsing manual.",
  "Local mode": "Modo local",
  "OpenAI is available for structured resume parsing and candidate matching.":
    "OpenAI está disponível para análise estruturada de currículos e matching de candidatos.",
  "PDFs with embedded text are analyzed locally, without API credits.": "PDFs com texto embutido são analisados localmente, sem créditos de API.",
  "Preparing candidate profile and match signals": "Preparando perfil do candidato e sinais de match",
  "Reading uploaded resume": "Lendo currículo enviado",
  "Resume analysis in progress": "Análise do currículo em andamento",
  "Saving review data to the CRM": "Salvando dados de revisão no CRM",
  "Smart local AI": "IA local inteligente",
  "Smart local AI review": "Revisão por IA local inteligente",
  "Smart local matching": "Matching local inteligente",
  "Smart local parsing and matching are active without API spend.": "Parsing e matching locais inteligentes estão ativos sem gasto de API.",
  "Smart resume parser": "Parser inteligente de currículo",
  "The parser is reading the file, extracting resume signals, and preparing the candidate record.":
    "O parser está lendo o arquivo, extraindo sinais do currículo e preparando o registro do candidato.",
  "This usually takes a few seconds. Keep this tab open while the parser works.":
    "Isso geralmente leva alguns segundos. Mantenha esta aba aberta enquanto o parser trabalha.",
  "Ship full-stack product features across recruiter and candidate workflows": "Entregar features full-stack nos fluxos de recrutador e candidato",
  "Ship polished product UI for review-heavy workflows": "Entregar UI de produto polida para fluxos com muita revisão",
  "Confirming the uploaded file": "Confirmando o arquivo enviado",
  "Reading resume text locally": "Lendo o texto do curriculo localmente",
  "Resume reviewed locally and saved to the candidate CRM.": "Curriculo revisado localmente e salvo no CRM de candidatos.",
  "Resume saved for review. The local reader did not find enough structured data, so you can complete it from the profile.": "Curriculo salvo para revisao. A leitura local nao encontrou dados estruturados suficientes, entao voce pode completar pelo perfil.",
  "Resume review could not be completed automatically. The file was saved for manual review.": "A revisao do curriculo nao pode ser concluida automaticamente. O arquivo foi salvo para revisao manual.",
  "Resume reviewed locally. Review extracted data before applying it.": "Curriculo revisado localmente. Revise os dados extraidos antes de aplicar.",
  "Resume saved for local review. Add readable resume text if this PDF is scanned or image-only.": "Curriculo salvo para revisao local. Adicione o texto legivel se este PDF for escaneado ou somente imagem.",
  "No file selected yet.": "Nenhum arquivo selecionado ainda.",
  "Choose file": "Escolher arquivo",
  "Optional text for scanned PDF": "Texto opcional para PDF escaneado",
  "Paste the resume text only if the PDF is scanned, image-only, or the local reader cannot extract text.": "Cole o texto do curriculo somente se o PDF for escaneado, imagem ou se a leitura local nao conseguir extrair texto.",
  "Upload a PDF or text file. The review runs locally and does not require API credits.": "Envie um PDF ou arquivo de texto. A revisao roda localmente e nao exige creditos de API.",
  "Smart local resume review": "Revisao local inteligente de curriculo",
  "Aptelys reads embedded text, detects profile signals, and saves the review without external AI credits.": "A Aptelys le texto embutido, detecta sinais do perfil e salva a revisao sem creditos externos de IA.",
  "Reviewing resume": "Revisando curriculo",
  "Review resume": "Revisar curriculo",
  "Resume review in progress": "Revisao do curriculo em andamento",
  "Aptelys is reading the file, extracting resume signals, and preparing the candidate record.": "A Aptelys esta lendo o arquivo, extraindo sinais do curriculo e preparando o registro do candidato.",
  "Aptelys is reading the attachment and preparing extracted data for recruiter review.": "A Aptelys esta lendo o anexo e preparando dados extraidos para revisao do recrutador.",
  "File received": "Arquivo recebido",
  "Local text review": "Revisao local do texto",
  "Candidate profile signals": "Sinais do perfil do candidato",
  "Local review": "Revisao local",
  "Uploads, local parsing, and recruiter review all write into the same candidate records.": "Uploads, analise local e revisao do recrutador gravam nos mesmos registros de candidato.",
  "Resume saved. The local reader did not find enough readable text, so open the profile and add resume text if the PDF is scanned or image-only.": "Curriculo salvo. A leitura local nao encontrou texto legivel suficiente, entao abra o perfil e adicione o texto do curriculo se o PDF for escaneado ou somente imagem.",
  "Candidate deleted from this workspace.": "Candidato excluido deste workspace.",
  "Candidate was not found in this workspace.": "Candidato nao encontrado neste workspace.",
  "Danger zone": "Zona de risco",
  "Remove this candidate and all related recruiting records from this workspace.": "Remova este candidato e todos os registros de recrutamento relacionados deste workspace.",
  "Delete candidate": "Excluir candidato",
  "Deleting candidate": "Excluindo candidato",
  "Candidate actions": "Acoes do candidato",
  "Copy email": "Copiar email",
  "Email copied": "Email copiado",
};

const PORTUGUESE_PATTERNS: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
  [/^(\d+) events synced to Google Calendar\. Failed syncs need reconnect or retry\.$/, (match) => `${match[1]} eventos sincronizados com Google Calendar. Falhas de sincronização precisam de reconexão ou nova tentativa.`],
  [/^(\d+) Google account connected\. (\d+) interview events synced\.$/, (match) => `${match[1]} conta Google conectada. ${match[2]} eventos de entrevista sincronizados.`],
  [/^(\d+) queued emails and (\d+) failed or bounced deliveries\.$/, (match) => `${match[1]} emails enfileirados e ${match[2]} entregas com falha ou devolvidas.`],
  [/^(\d+) active self-scheduling links\. (\d+) public applications received\.$/, (match) => `${match[1]} links de autoagendamento ativos. ${match[2]} candidaturas públicas recebidas.`],
  [/^(\d+)\/(\d+) resumes parsed\. Review failed or low-confidence parses before matching\.$/, (match) => `${match[1]}/${match[2]} currículos analisados. Revise análises com falha ou baixa confiança antes do matching.`],
  [/^(.+) from (.+)\. (\d+) queued, (\d+) failed or bounced\.$/, (match) => `${match[1]} de ${match[2]}. ${match[3]} enfileirados, ${match[4]} com falha ou devolvidos.`],
  [/^(\d+) active applications$/, (match) => `${match[1]} candidaturas ativas`],
  [/^(\d+) active requisitions$/, (match) => `${match[1]} requisições ativas`],
  [/^(\d+) applications$/, (match) => `${match[1]} candidaturas`],
  [/^(\d+) applications moved to screening\.$/, (match) => `${match[1]} candidaturas movidas para triagem.`],
  [/^(\d+) applications rejected\.$/, (match) => `${match[1]} candidaturas rejeitadas.`],
  [/^(\d+) candidates? in process$/, (match) => `${match[1]} candidatos em processo`],
  [/^(\d+) matching candidate$/, (match) => `${match[1]} candidato encontrado`],
  [/^(\d+) matching candidates$/, (match) => `${match[1]} candidatos encontrados`],
  [/^(\d+) resumes marked reviewed\.$/, (match) => `${match[1]} currículos marcados como revisados.`],
  [/^(\d+) scored applications$/, (match) => `${match[1]} candidaturas pontuadas`],
  [/^(\d+) scheduling links created or reused\.$/, (match) => `${match[1]} links de agendamento criados ou reutilizados.`],
  [/^(\d+) selected fields$/, (match) => `${match[1]} campos selecionados`],
  [/^(\d+) stages$/, (match) => `${match[1]} etapas`],
  [/^(\d+) total requisitions$/, (match) => `${match[1]} requisições no total`],
  [/^(\d+)d avg in stage$/, (match) => `${match[1]}d em média na etapa`],
  [/^(\d+)d avg time to hire$/, (match) => `${match[1]}d em média até contratar`],
  [/^(\d+)% interview rate$/, (match) => `${match[1]}% taxa de entrevista`],
  [/^(\d+)% match$/, (match) => `${match[1]}% match`],
  [/^(\d+)% offer rate$/, (match) => `${match[1]}% taxa de oferta`],
  [/^Saved\. (\d+) automation email queued\.$/, (match) => `Salvo. ${match[1]} email de automação enfileirado.`],
];

const LOWERCASE_ENGLISH_TO_PORTUGUESE = Object.fromEntries(
  Object.entries(ENGLISH_TO_PORTUGUESE).map(([english, portuguese]) => [english.toLowerCase(), portuguese]),
);

const PORTUGUESE_TO_ENGLISH = {
  ...Object.fromEntries(Object.entries(ENGLISH_TO_PORTUGUESE).map(([english, portuguese]) => [portuguese, english])),
  ...Object.fromEntries(Object.keys(SITE_COPY.pt).map((key) => [SITE_COPY.pt[key], SITE_COPY.en[key]])),
};

export function getCanonicalEnglishText(text: string) {
  return PORTUGUESE_TO_ENGLISH[text] ?? text;
}

const PARTIAL_PORTUGUESE_REPLACEMENTS: Array<[string, string]> = [
  ["Application Received", "Candidatura recebida"],
  ["Interview confirmation", "Confirmação de entrevista"],
  ["Screening invite", "Convite de triagem"],
  ["Offer follow-up", "Follow-up de oferta"],
  ["Rejection notice", "Aviso de rejeição"],
  ["Moved To Stage", "Movido para etapa"],
  ["Manual review", "Revisão manual"],
  ["Current pipeline", "Pipeline atual"],
  ["Next step for", "Próximo passo para"],
  ["Senior Full Stack Engineer", "Engenheiro Full Stack Sênior"],
  ["Backend Platform Engineer", "Engenheiro de Plataforma Backend"],
  ["Recruiting Operations Manager", "Gerente de Operações de Recrutamento"],
  ["AI Product Engineer", "Engenheiro de Produto IA"],
  ["Recruiting Operations Lead", "Líder de Operações de Recrutamento"],
  ["Full Time", "Tempo integral"],
  ["Remote Brazil", "Remoto Brasil"],
  ["Remote LATAM", "Remoto LATAM"],
  ["Hybrid Lisbon", "Híbrido Lisboa"],
  ["No email", "Sem email"],
  ["No phone", "Sem telefone"],
  ["Not provided", "Não informado"],
  ["Pending parse", "Análise pendente"],
  ["Active rules send messages when candidates move stage, schedule interviews, or get rejected.", "Regras ativas enviam mensagens quando candidatos mudam de etapa, agendam entrevistas ou são rejeitados."],
  ["candidates in process", "candidatos em processo"],
  ["avg in stage", "média na etapa"],
  ["public applications received", "candidaturas públicas recebidas"],
  ["active self-scheduling links", "links de autoagendamento ativos"],
  ["AI-ready", "Pronto para IA"],
  ["Attention", "Atenção"],
  ["People", "Pessoas"],
  ["Resume uploaded and waiting for OpenAI parsing.", "Currículo enviado e aguardando análise com OpenAI."],
  ["Add OPENAI_API_KEY to enable AI extraction.", "Adicione OPENAI_API_KEY para habilitar extração com IA."],
  ["your profile looks aligned with", "seu perfil parece alinhado com"],
  ["Please choose a time for a recruiter screen.", "Escolha um horário para uma triagem com recrutador."],
  ["your interview is confirmed for", "sua entrevista está confirmada para"],
  ["We are looking forward to speaking with you.", "Estamos ansiosos para conversar com você."],
  ["thanks for applying to", "obrigado por se candidatar para"],
  ["We received your resume and our team will review your profile soon.", "Recebemos seu currículo e nosso time revisará seu perfil em breve."],
  ["thank you for your time in the", "obrigado pelo seu tempo no processo de"],
  ["We will not be moving forward at this stage, but we appreciate your interest.", "Não seguiremos em frente nesta etapa, mas agradecemos seu interesse."],
  ["we are excited to discuss offer details and next steps with you.", "estamos animados para conversar sobre detalhes da oferta e próximos passos com você."],
  ["Hi ", "Olá "],
  ["Thursday", "Quinta-feira"],
  ["Wednesday", "Quarta-feira"],
  ["Tuesday", "Terça-feira"],
  ["Monday", "Segunda-feira"],
  ["Friday", "Sexta-feira"],
  ["Saturday", "Sábado"],
  ["Sunday", "Domingo"],
  ["Thu", "Qui"],
  ["Screening", "Triagem"],
  ["Interview", "Entrevista"],
  ["Offer", "Oferta"],
  ["Hired", "Contratado"],
  ["Rejected", "Rejeitado"],
  ["Applied", "Aplicado"],
  ["Scheduled", "Agendado"],
  ["Delivered", "Entregue"],
  ["Failed", "Falhou"],
  ["Queued", "Enfileirado"],
  ["Status", "Status"],
  ["Source", "Fonte"],
  ["Experience", "Experiência"],
  ["Education", "Educação"],
  ["skills", "competências"],
  ["Skills", "Competências"],
  ["Emails", "E-mails"],
  ["Unknown", "Não informado"],
  ["parsing", "análise"],
  ["parses", "análises"],
  ["Resume", "Currículo"],
  ["Calendar", "Calendário"],
  ["Analytics", "Análises"],
];

const PARTIAL_PORTUGUESE_REPLACEMENT_RULES = [...PARTIAL_PORTUGUESE_REPLACEMENTS].sort(
  ([first], [second]) => second.length - first.length,
).map(([english, portuguese]) => ({
  pattern: new RegExp(english.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g"),
  portuguese,
}));

function applyPartialPortugueseTranslations(text: string) {
  let translated = text;

  PARTIAL_PORTUGUESE_REPLACEMENT_RULES.forEach(({ pattern, portuguese }) => {
    translated = translated.replace(pattern, portuguese);
  });

  return translated === text ? null : translated;
}

export function getLanguageCopy(language: SiteLanguage, key: string) {
  return SITE_COPY[language][key] ?? SITE_COPY.en[key] ?? key;
}

export function translateText(text: string, language: SiteLanguage): string {
  if (language === "en") {
    return text;
  }

  const exact = ENGLISH_TO_PORTUGUESE[text];

  if (exact) {
    return exact;
  }

  const lowerExact = LOWERCASE_ENGLISH_TO_PORTUGUESE[text.toLowerCase()];

  if (lowerExact) {
    return lowerExact;
  }

  for (const [pattern, translate] of PORTUGUESE_PATTERNS) {
    const match = text.match(pattern);
    if (match) {
      return translate(match);
    }
  }

  if (text.includes(" - ")) {
    return text
      .split(" - ")
      .map((part) => translateText(part, language))
      .join(" - ");
  }

  const partial = applyPartialPortugueseTranslations(text);

  if (partial) {
    return partial;
  }

  return text;
}
